FORMAT: 1A

# Blog API

Simple API to create authored blog posts. 

# Blog Posts [/blog/posts]

+ Attributes (Blog Post)

## Create a Blog Post [POST]

+ Attributes (Blog Post)

+ Response 201

+ Request

        {
          "title": "Let's try with title only"
        }

+ Response 400 (application/json)

## Retrieve a Blog Post [GET /blog/posts/{id}]

+ Parameters
    + id: `b5c23fa6-ba19-47eb-8d3c-fae77db1b3c3` (string, required)

+ Response 200 (application/json)
    + Attributes (Blog Post)

## Delete a Blog Post [DELETE /blog/posts/{id}]

+ Parameters
    + id: `b5c23fa6-ba19-47eb-8d3c-fae77db1b3c3` (string, required)

+ Response 200

# Authors [/blog/authors]

+ Attributes (Person)

## Create an Author [POST]

+ Attributes (Person)

+ Response 201

## Retrieve an Author [GET /blog/authors/{id}]

+ Parameters
    + id: `c4e517b4-74ca-446d-a1df-c254cbb5179d` (string, required)

+ Response 200
    + Attributes (Person)

# Data Structures

## Person (object)
+ id: `c4e517b4-74ca-446d-a1df-c254cbb5179d` (string, required)
+ name: Zaphod (string, optional)
+ surname: Beeblebrox (string, optional)
+ email: zaphod@beeblebrox.space (string, required)

## Blog Post (object)
+ title: How to build good APIs (string, required)
+ content: Start with design and take it from there (string, required)
+ created_date: `2016-05-12` (string, required)
+ author (Person, required)
+ category (Category, optional)

## Category (object)
+ name: API Design (string, required)
+ description: posts on API Design and related (string, optional)